export const templates = [
  { name: "TikTok Punch", description: "Cortes rápidos + transiciones de impacto", format: "9:16" },
  { name: "Reel Moderno", description: "Dinámico para Instagram Reels", format: "9:16" },
  { name: "Magistro Story", description: "Narrativa automática con ritmo", format: "9:16" },
  { name: "Vlog Diario", description: "Intro limpia + bloques de highlights", format: "16:9" },
  { name: "Travel Cinematic", description: "Transiciones suaves estilo viaje", format: "16:9" },
  { name: "Promo Producto", description: "Pantallas cortas para vender rápido", format: "1:1" },
  { name: "Antes / Después", description: "Comparativa visual con impacto", format: "4:5" },
  { name: "Beat Sync", description: "Edición al ritmo de música", format: "9:16" },
  { name: "Tutorial Express", description: "Paso a paso en clips cortos", format: "16:9" },
  { name: "Slideshow Pro", description: "Fotos animadas con timing preciso", format: "16:9" },
  { name: "Vintage Glow", description: "Color nostálgico y textura suave", format: "4:5" },
  { name: "Minimal Clean", description: "Diseño limpio y transiciones simples", format: "1:1" },
  { name: "Celebración Pop", description: "Brillos, energía y ritmo", format: "9:16" },
  { name: "Loop Infinito", description: "Salida-entrada conectada para loop", format: "1:1" },
  { name: "Corporate Fast", description: "Presentación profesional ágil", format: "16:9" },
];
